spring:
  application:
    name: interview
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test_db;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

logging:
  level:
    org:
      springframework:
        transaction: TRACE
        orm:
          jpa:
            JpaTransactionManager: DEBUG
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        orm:
          jdbc:
            bind: TRACE
        SQL: DEBUG